from .fcn import FCN8
from .segnet import SegNet
from .segnet import SegResNet
from .enet import ENet
from .gcn import GCN
from .deeplabv3_plus import DeepLab
from .duc_hdc import DeepLab_DUC_HDC
from .upernet import UperNet
from .pspnet import PSPNet
from .pspnet import PSPDenseNet
from .hrnetv2 import HRNetV2
from .bisenet import BiSeNet
from .unet import U_Net, R2U_Net, AttU_Net, R2AttU_Net
from .icnet import ICNet
from .hrnetv2_ocr import HRNetV2_OCR
from .encnet import EncNet
from .ocnet import OCNet
from .espnetv2 import ESPNetV2
from .dfanet import DFANet
from .danet import DANet
from .denseaspp import DenseASPP
from .dunet import DUNet
from .cgnet import CGNet
from .lednet import LEDNet
from .mobilenetv3 import MobileNetV3_Small, MobileNetV3_Large
from .shufflenetv2 import ShuffleNetV2
from .efficientnet import EfficientNetSeg
from .shufflenetv2plus import ShuffleNetV2_Plus
from .encnet_jpu import EncNet_JPU
from .hrnetv2_ocr_inference import HRNetV2_OCR_Inference
from .hrnetv2_ocr_nearest import HRNetV2_OCR_Nearest